version: "3.8"
services:
  npm:
    image: 'node:16'
    ports:
      - '3000:3000'
    working_dir: '/code/pizzeria/backend'
    entrypoint: ['npm']
    volumes:
      - ./:/code/pizzeria/backend
  start:
    image: 'node:16'
    ports:
      - '3000:3000'
    working_dir: '/code/pizzeria/backend'
    command: ['npm', 'start']
    volumes:
      - ./:/code/pizzeria/backend
