version: "3.8"
services:
  start:
    image: 'node:16'
    ports:
      - '3000:3000'
    working_dir: '/code/pizzeria/backend'
    command: ['npm', 'start']
    volumes:
      - ./:/code/pizzeria/backend
    depends_on:
      - postgres
  npm:
    image: 'node:16'
    working_dir: '/code/pizzeria/backend'
    entrypoint: ['npm']
    volumes:
      - ./:/code/pizzeria/backend
    depends_on:
      - postgres
  postgres:
    image: 'postgres:14.4'
    environment:
      - POSTGRES_USER=pizzeria
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=pizzeria
    ports:
      - '5432:5432'
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data